# Generated by Django 5.1.6 on 2025-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='basic_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gross_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hra_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
