# Generated by Django 5.1.6 on 2025-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Untitled Article', max_length=100),
        ),
    ]
